app:
  build: .
  command: npm start
  volumes:
    - .:/app
    - /app/node_modules
  ports:
    - "3000:3000"
  links:
    - mongodb

mongodb:
  image: mongo:latest
  ports:
    - "27017:27017"
    - "28017:28017"
  environment:
    AUTH: 'no'
